language: cpp
os: osx
osx_image: xcode11.5
compiler: clang

cache:
  ccache: true
  directories:
  - "$HOME/Library/Caches/Homebrew"
before_cache:
- brew cleanup

stages:
- name: test
  if: type IN (pull_request) OR tag IS present
- name: deploy
  if: tag IS present

jobs:
  include:
  - stage: test
    script:
    - "./.travis/install-deps.sh"
    - export PATH="/usr/local/opt/ccache/libexec:$PATH";
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - cmake --build . -- -j2
    - ctest -V
  - stage: deploy
    script:
    - "./.travis/install-deps.sh"
    - export PATH="/usr/local/opt/ccache/libexec:$PATH";
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . -- -j2
    - cmake --build . --target bundle
    deploy:
      provider: releases
      skip_cleanup: true
      api_key:
        secure: KEa0dhrttsQiZ6NTKSyIOIqYoBw64wCxK85yKYJQlJBP6bLZilFxy0brkiwKu2ur0EDmkOWOxlG9RP2YEuPL7Pc0Vym56CVQXFqATJ7HsK0fgl6LqkI9X0AjE+tew2Pf/eQIXSJF2bpGIFphzbG+Fy62/+n4axy+1vGbyZY9JkWbeT3uPcr6ZwGyR4I0ImFDskCkL7bSzMBaN7Z5sMjoJyckPCDTLO0ekHN2Q1zLLMR9eFa5KGaym3u25BzYh1GTUbqRhV3LP72Pslqemwfd0GKGiaNyLyw5EW403esxvXm0n6SpvvF44m7DiECCkDFnDW2cr5NLUUWBeOXXJsgTHHVlq6lTbt1pxkRZRoFDRpzkhZPzw/rV4ikVDEpb4FyIJnQ6pwSNwTkJlqqiM7YNMZafctADqmS+18mF4VQVTr244MtgZa6U+n31peYnQgVAxfOfIHGYiNaWXA/dCgc5BfIct2UWk8q2STLGn3FGnT+xJc0rwfRaSevNBx1I9mwPnkLlHfWbZX8hmusoRfOTZtyatieX0lETBJvk1hP5bJmYmbrTjeFutFJn2UX14+A615aUOTVFggElSasv6t8VXSGcJ/EzsFtpq5ZZcmz4fMG6I978MM2iNnLLOcRXKP9423RgLmyahlzG5t1Lm1mGnJMykxWEuX2beNqzkaOlwQk=
      file: src/ELook.dmg
      on:
        branch: master
        tags: true
